[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "42ccde8a40866413e6a9ab24f19df6d30062fc8f"
libc = "glibc"
os = "linux"

    [[Openresty.download]]
    sha256 = "6b03c719a02f87e43c7ce34063e8f473349e9b0e697bef454abe5e9e32a5183d"
    url = "https://github.com/JuliaBinaryWrappers/Openresty_jll.jl/releases/download/Openresty-v1.27.1+0/Openresty.v1.27.1.x86_64-linux-gnu.tar.gz"
[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "fc38148acf763365e5dda80e71386bb27840a7f1"
libc = "musl"
os = "linux"

    [[Openresty.download]]
    sha256 = "b10286b8cb904670ca03c874063aef2bc3dbe272ebe7abf56bae645a1260e2f7"
    url = "https://github.com/JuliaBinaryWrappers/Openresty_jll.jl/releases/download/Openresty-v1.27.1+0/Openresty.v1.27.1.x86_64-linux-musl.tar.gz"
