[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "8734ebb1794d346e38f491a80ee184ee48ecb02a"
libc = "glibc"
os = "linux"

    [[Openresty.download]]
    sha256 = "a9fedc0189393e125dd70c87625a0d619d81466fd2a8124a0bc9b708af38d595"
    url = "https://github.com/JuliaBinaryWrappers/Openresty_jll.jl/releases/download/Openresty-v1.19.9+0/Openresty.v1.19.9.x86_64-linux-gnu.tar.gz"
[[Openresty]]
arch = "x86_64"
git-tree-sha1 = "c37d42aaed507b0fbccc103abbc05b7515034e10"
libc = "musl"
os = "linux"

    [[Openresty.download]]
    sha256 = "c4963feba4821df71eed81fe95d369a98688659eba257a6784bab4cbf2278e31"
    url = "https://github.com/JuliaBinaryWrappers/Openresty_jll.jl/releases/download/Openresty-v1.19.9+0/Openresty.v1.19.9.x86_64-linux-musl.tar.gz"
